// Hostile units belong to the private Cenexis operation or the locked-down
// building's infrastructure. Solace's ordinary service robots remain civilians.
export const SOLACE_ENEMIES={
 solaceSecurity:{speed:30,name:'Cenexis Recovery Officer',hp:630,attack:120,charge:160,xp:820,credits:105,portrait:'water-enemies',frame:'water-3',kind:'human',noHelp:true,opening:'“Private recovery order. Bellwether subject, remain where you are.”',attackText:'A capture baton strikes your shoulder!',chargedText:'A shock shield drives forward!'},
 solaceDrone:{speed:65,name:'Cenexis Recovery Drone',hp:470,attack:108,charge:149,xp:690,credits:80,portrait:'fairmont-enemy-test-drone-battle',mapTexture:'fairmont-enemy-test-drone-map',kind:'robot',noHelp:true,opening:'RESONANCE MATCH VERIFIED. RECOVERY CONDITION: ALIVE.',attackText:'A stun dart catches its target!',chargedText:'A focused restraint pulse!'},
 residentialCleaner:{speed:30,name:'Residential Floor Steward',hp:530,attack:116,charge:155,xp:710,credits:75,portrait:'solace-cleaner-battle',mapTexture:'solace-cleaner-map',kind:'robot',helper:'residentialCleaner',opening:'SAFETY OVERRIDE: RESIDENTIAL ACCESS REVOKED.',attackText:'Its buffer sweeps across the floor!',chargedText:'A locked-wheel restraint rush!'},
 residentialPorter:{speed:25,name:'Autonomous Luggage Porter',hp:720,attack:126,charge:172,xp:840,credits:92,portrait:'solace-porter-battle',mapTexture:'solace-porter-map',kind:'robot',helper:'residentialCleaner',opening:'LUGGAGE ROUTE OVERRIDDEN. SUBJECT TRANSFER REQUIRED.',attackText:'A padded loading arm drives forward!',chargedText:'A hydraulic cargo clamp snaps shut!'},
 residentialMaintenance:{speed:28,name:'Building Maintenance Unit',hp:690,attack:131,charge:181,xp:910,credits:96,portrait:'solace-maintenance-battle',mapTexture:'solace-maintenance-map',kind:'robot',helper:'residentialPorter',opening:'SERVICE MODE OVERRIDDEN. CONTAINMENT TAKES PRIORITY.',attackText:'An insulated tool arm strikes!',chargeText:'It braces against the floor and winds a restraint cable.',chargedText:'A powered cable reel pulls tight!'},
 solaceResponse:{speed:34,name:'Cenexis Containment Specialist',hp:840,attack:143,charge:194,xp:1120,credits:112,portrait:'water-enemies',frame:'water-3',kind:'human',helper:'residentialMaintenance',opening:'“Rooftop recovery team. Do not injure the subject beyond transport tolerance.”',attackText:'An electrified restraint baton connects!',chargedText:'A coordinated shock-shield strike!'},
 containment8:{speed:34,name:'Special Containment Unit · Series 8',hp:2900,attack:145,charge:193,xp:2900,credits:380,portrait:'solace-containment-battle',frame:'__BASE',mapTexture:'solace-containment-map',kind:'robot',boss:true,noHelp:true,sillyRate:.05,adaptive:true,containment:true,opening:'The recovery order specifies alive. I intend to comply.',attackText:'COMPLIANCE PULSE: a directional stun burst!',chargeText:'Building barriers align around a charged restraint field.',chargedText:'ENVIRONMENTAL OVERRIDE: the rooftop capture field closes!'}
};
