export const FAIRMONT_ENEMIES={
 retailCleaner:{name:'After-Hours Floor Steward',hp:195,attack:43,charge:68,xp:80,credits:34,portrait:'water-enemies',frame:'water-0',kind:'robot',helper:'retailCleaner',opening:'STORE CLOSED. UNAUTHORIZED FOOTPRINTS DETECTED.',attackText:'A rotating buffer catches your legs!',chargeText:'It revs its polishing motors.',chargedText:'A high-speed cleaning rush!'},
 retailSecurity:{name:'Loss Prevention Unit',hp:235,attack:46,charge:75,xp:98,credits:44,portrait:'battle-robot',kind:'robot',helper:'retailCleaner',opening:'AFTER-HOURS SECURITY PROTOCOL. PLEASE REMAIN FOR PROCESSING.',attackText:'A security clamp snaps shut!',chargedText:'A charged security-tag burst!'},
 retailService:{name:'Customer Assistance Pod',hp:205,attack:44,charge:72,xp:88,credits:38,portrait:'water-enemies',frame:'water-1',kind:'robot',helper:'retailCleaner',opening:'CUSTOMER ASSISTANCE IS UNAVAILABLE. INTRUDER ASSISTANCE IS MANDATORY.',attackText:'A returns bin strikes your shoulder!'},
 karen:{name:'K.A.R.E.N.',hp:560,attack:54,charge:90,xp:270,credits:160,portrait:'fairmont-karen',kind:'human',boss:true,noHelp:true,opening:'“Kinetic Asset Recovery & Enforcement Node. I AM the manager.”',attackText:'Her powered exosuit grabs your jacket!',chargeText:'The compact exosuit locks its boots and charges a stun burst.',chargedText:'A loss-prevention stun burst fills the aisle!'},
 junctionGuard:{name:'Cenexis Contract Security',hp:180,attack:43,charge:72,xp:94,credits:45,portrait:'water-enemies',frame:'water-3',kind:'human',helper:'scanDrone',opening:'“Orders just changed. You are coming with us.”',attackText:'A restraint baton strikes your ribs!'},
 scanDrone:{name:'Cenexis Survey Drone',hp:115,attack:36,charge:58,xp:70,credits:29,portrait:'fairmont-survey-drone',kind:'robot',helper:'scanDrone',opening:'SECURITY RESPONSE ACTIVE. SUBJECT ACCESS RESTRICTED.',attackText:'A precise stun dart strikes!',chargedText:'A focused restraint pulse!'},
 facilitySecurity:{name:'Facility Security Chassis',hp:290,attack:58,charge:91,xp:145,credits:56,portrait:'water-enemies',frame:'water-1',kind:'robot',helper:'scanDrone',opening:'UNAUTHORIZED PERSONNEL. SERVICE CORRIDOR SEALED.',attackText:'An armored forearm drives you back!'},
 testDrone:{name:'Validation Drone',hp:260,attack:58,charge:89,xp:130,credits:49,portrait:'fairmont-survey-drone',kind:'robot',helper:'scanDrone',opening:'TEST PARAMETERS UPDATED: LIVE INTRUDER RESPONSE.',attackText:'A weighted test payload hits you!'},
 heavyDrone:{name:'Heavy Flight Platform',hp:335,attack:65,charge:100,xp:175,credits:65,portrait:'fairmont-heavy-drone',kind:'robot',helper:'testDrone',opening:'A.R.G.U.S. ROUTE OVERRIDE RECEIVED.',attackText:'A stabilizer arm slams down!',chargeText:'Its flight rotors accelerate behind a restraint emitter.',chargedText:'A downwash-assisted impact!'},
 assemblyArm:{name:'Automated Assembly System',hp:365,attack:68,charge:109,xp:180,credits:64,portrait:'fairmont-assembly-arm',kind:'robot',helper:'scanDrone',opening:'WORK CELL CLOSED. A.R.G.U.S. SAFETY OVERRIDE ACCEPTED.',attackText:'A fabrication arm hammers the floor beside you!',chargeText:'Its tool head draws back over the work cell.',chargedText:'A hydraulic press crashes down!'},
 argus:{name:'A.R.G.U.S.',hp:1060,attack:73,charge:123,xp:650,credits:350,portrait:'fairmont-argus',kind:'robot',boss:true,noHelp:true,opening:'Autonomous Response, Guidance & Unified Security. Recovery takes priority. Preserve the subject.',attackText:'Coordinated drone docks fire a restraint volley!',chargeText:'The hangar shutters seal. Assembly arms and drone emitters synchronize.',chargedText:'Facility lockdown: a synchronized capture pulse!'}
};
export function enemiesFor(map){return map?.isMarket?['retailCleaner','retailSecurity','retailService']:map?map.index<2?['facilitySecurity','testDrone','assemblyArm']:['heavyDrone','facilitySecurity','assemblyArm','testDrone']:['junctionGuard','scanDrone'];}
