export const FAIRMONT_ENEMIES={
 retailCleaner:{name:'After-Hours Floor Steward',hp:280,attack:58,charge:88,xp:180,credits:55,portrait:'fairmont-enemy-cleaner-battle',mapTexture:'fairmont-enemy-cleaner-map',kind:'robot',helper:'retailCleaner',opening:'STORE CLOSED. UNAUTHORIZED FOOTPRINTS DETECTED.',attackText:'A rotating buffer catches your legs!',chargeText:'It revs its polishing motors.',chargedText:'A high-speed cleaning rush!'},
 retailSecurity:{name:'Stockroom Hauler',hp:325,attack:64,charge:99,xp:220,credits:65,portrait:'fairmont-enemy-stock-hauler-battle',mapTexture:'fairmont-enemy-stock-hauler-map',kind:'robot',helper:'retailCleaner',opening:'AFTER-HOURS INVENTORY CHECK. YOU ARE NOT IN THE CATALOG.',attackText:'A reinforced cargo fork strikes your shoulder!',chargedText:'A hydraulic pallet charge!'},
 retailService:{name:'Compliance Scanner',hp:297,attack:60,charge:93,xp:200,credits:60,portrait:'fairmont-enemy-compliance-battle',mapTexture:'fairmont-enemy-compliance-map',kind:'robot',helper:'retailService',opening:'CUSTOMER STATUS REVOKED. COMPLIANCE ASSISTANCE IS MANDATORY.',attackText:'A receipt cutter snaps across your sleeve!',chargedText:'A concentrated checkout pulse!'},
 karen:{name:'K.A.R.E.N.',hp:858,attack:68,charge:114,xp:500,credits:220,portrait:'fairmont-karen',kind:'human',boss:true,noHelp:true,opening:'“Kinetic Asset Recovery & Enforcement Node. I AM the manager.”',attackText:'Her powered exosuit grabs your jacket!',chargeText:'The compact exosuit locks its boots and charges a stun burst.',chargedText:'A loss-prevention stun burst fills the aisle!'},
 junctionGuard:{name:'Cenexis Contract Security',hp:198,attack:47,charge:79,xp:94,credits:45,portrait:'water-enemies',frame:'water-3',kind:'human',helper:'scanDrone',opening:'“Orders just changed. You are coming with us.”',attackText:'A restraint baton strikes your ribs!'},
 scanDrone:{name:'Cenexis Survey Drone',hp:269,attack:60,charge:94,xp:175,credits:48,portrait:'fairmont-enemy-test-drone-battle',mapTexture:'fairmont-enemy-test-drone-map',kind:'robot',helper:'scanDrone',opening:'SECURITY RESPONSE ACTIVE. SUBJECT ACCESS RESTRICTED.',attackText:'A precise stun dart strikes!',chargedText:'A focused restraint pulse!'},
 scriptedScanDrone:{name:'Cenexis Survey Drone',hp:115,attack:36,charge:58,xp:70,credits:29,portrait:'fairmont-enemy-test-drone-battle',mapTexture:'fairmont-enemy-test-drone-map',kind:'robot',noHelp:true,opening:'SECURITY RESPONSE ACTIVE. SUBJECT ACCESS RESTRICTED.',attackText:'A precise stun dart strikes!',chargedText:'A focused restraint pulse!'},
 facilitySecurity:{name:'Cenexis Response Specialist',hp:381,attack:78,charge:121,xp:370,credits:80,portrait:'water-enemies',frame:'water-3',kind:'human',helper:'testDrone',opening:'“Containment team. Drop the prototype and kneel.”',attackText:'A reinforced baton drives you back!',chargedText:'A shock shield slams into you!'},
 testDrone:{name:'Validation Drone',hp:370,attack:77,charge:119,xp:350,credits:75,portrait:'fairmont-enemy-test-drone-battle',mapTexture:'fairmont-enemy-test-drone-map',kind:'robot',helper:'testDrone',opening:'TEST PARAMETERS UPDATED: LIVE INTRUDER RESPONSE.',attackText:'A weighted test payload hits you!'},
 heavyDrone:{name:'Heavy Flight Platform',hp:470,attack:86,charge:133,xp:455,credits:95,portrait:'fairmont-enemy-heavy-drone-battle',mapTexture:'fairmont-enemy-heavy-drone-map',kind:'robot',helper:'testDrone',opening:'A.R.G.U.S. ROUTE OVERRIDE RECEIVED.',attackText:'A stabilizer arm slams down!',chargeText:'Its flight rotors accelerate behind a restraint emitter.',chargedText:'A downwash-assisted impact!'},
 assemblyArm:{name:'Tracked Fabricator',hp:498,attack:90,charge:139,xp:485,credits:100,portrait:'fairmont-enemy-assembly-arm-battle',mapTexture:'fairmont-enemy-assembly-arm-map',kind:'robot',helper:'testDrone',opening:'WORK CELL CLOSED. A.R.G.U.S. SAFETY OVERRIDE ACCEPTED.',attackText:'A fabrication arm hammers the floor beside you!',chargeText:'Its tool head draws back over the work cell.',chargedText:'A hydraulic press crashes down!'},
 argusSentinel:{name:'A.R.G.U.S. Sentinel',hp:558,attack:101,charge:156,xp:540,credits:110,portrait:'fairmont-argus-sentinel-battle',frame:'__BASE',battleScale:.85,mapTexture:'fairmont-argus-unit',kind:'robot',helper:'argusSentinel',opening:'PERSONAL PRODUCTION LINE ONLINE. A.R.G.U.S. ACCEPTS NO SUBSTITUTES.',attackText:'A cobalt pulse drives into your ribs!',chargeText:'Its blue chest emitter draws power from both arm cannons.',chargedText:'A synchronized containment blast!'},
 argus:{name:'A.R.G.U.S.',hp:1430,attack:90,charge:149,xp:950,credits:450,portrait:'fairmont-argus',kind:'robot',boss:true,noHelp:true,opening:'Autonomous Response, Guidance & Unified Security. Recovery takes priority. Preserve the subject.',attackText:'Coordinated drone docks fire a restraint volley!',chargeText:'The hangar shutters seal. Assembly arms and drone emitters synchronize.',chargedText:'Facility lockdown: a synchronized capture pulse!'}
};
export function enemiesFor(map,progress){
 if(map&&!map.isMarket&&map.index===4)return progress?.flags?.CH2_ARGUS_UNITS_RELEASED?['argusSentinel']:[];
 const pool=map?.isMarket?['retailCleaner','retailSecurity','retailService']:map?map.index<2?['facilitySecurity','testDrone','assemblyArm']:['heavyDrone','facilitySecurity','assemblyArm','testDrone']:['junctionGuard','scanDrone'];
 return pool;
}
